[template]
src = "Caddyfile.tmpl"
dest = "/opt/app/conf/caddy/Caddyfile"
mode = "0700"
uid = 1002
gid = 1003
keys = [
    "/",
]
# caddy 服务默认是不开启的
reload_cmd = "/opt/app/current/bin/tmpl/mongodb.sh; appctl restartCaddy"