---
- name: create user mongod
  user:
    name: mongod
    groups: svc
    shell: /sbin/nologin
    create_home: false

- name: download app-agent (arm version)
  get_url:
    url: https://appcenter-agent.pek3a.qingstor.com/app-agent-linux-arm64.tar.gz
    dest: /tmp/app-agent-linux-arm64.tar.gz

- name: unarchive app-agent
  unarchive:
    src: /tmp/app-agent-linux-arm64.tar.gz
    dest: /tmp/
    remote_src: True

- name: install app-agent
  shell: /tmp/app-agent-linux-arm64/install.sh
  become: true
  become_user: root
  args:
    chdir: /tmp/app-agent-linux-arm64/
    creates: /opt/qingcloud/app-agent

- name: re-install ca-certificates
  apt:
    update_cache: yes
    name: ['ca-certificates']
    state: latest

- name: apt install jq, bc
  apt:
    name: ['jq','bc']
    update_cache: yes
    state: latest

- name: create group caddy
  group:
    name: caddy
    state: present

- name: create user caddy
  user:
    name: caddy
    groups: caddy
    shell: /sbin/nologin
    create_home: false

- name: install caddy binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: caddy
      pkg_version: "{{ caddy_version }}"
      pkg_url: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_arm64.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes

- name: install mongodb exporter binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: mongodb_exporter
      pkg_version: "{{ mongodb_exporter_version }}"
      pkg_url: https://github.com/percona/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-arm64.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: install node exporter binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: node_exporter
      pkg_version: "{{ node_exporter_version }}"
      pkg_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-arm64.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: install mongodb binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: mongodb
      pkg_version: "{{ mongodb_version }}"
      pkg_url: https://fastdl.mongodb.org/linux/mongodb-linux-arm64-ubuntu1604-{{ mongodb_version }}.tgz
      pkg_type: tgz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: copy app files
  copy:
    src: opt/app/current/
    dest: /opt/app/current/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=rx

- name: modify /opt/app/current/bin/ctl.sh
  shell: sed -i 's/local f; for f in $(find \/opt\/app\/current\/bin\/node\/ -name "$fileNames.sh"); do . $f; done/local f; for f in $(eval echo "{$fileNames}.sh"); do . \/opt\/app\/current\/bin\/node\/$f; done/' /opt/app/current/bin/ctl.sh

- name: install confd files
  include_role:
    name: confd-files-1.1.0

- name: clear syslog
  shell: ": > /var/log/syslog"